### ISSUE TITLE
New revision of wiimote: RVL-CNT-01-TR

### ISSUE THREAD

**Issue by rpavlik** [wiiuse/wiiuse#21]
I don't have one, but apparently there are breaking changes, at least to the bluetooth/hid product ID, etc.

http://glovepie.org/blog/2012/01/03/wii-remote-plus/
https://bugs.launchpad.net/wiican/+bug/954546

Per WiiBrew: "The newer Wiimote RVL-CNT-01-TR shuts down immediately upon receiving any HID output report if it has been turned on using the 1 + 2 method, although it works using the sync button. It is possible that authentication is now mandatory for the 1 + 2 temporary sync[check]." http://wiibrew.org/wiki/Wiimote

**Comment by janoc** [comment]
This is finally fixed in 0.15.2

**Comment by lachose1** [comment]
I still get this bug on Windows, all the older wiimotes work correctly. However, the latest version doesn't.

**Comment by janoc** [comment]
Open a new bug report/issue. This one is about supporting the -TR wiimote as such and that obviously works for you.

**Comment by janoc** [comment]
@lachose1 I do remember testing my -TR Wiimote using the basic (non-SDL) example included with Wiiuse and everything was working at least in my Linux. Is even that not working correctly for you? Your symptoms sound like you don't have a correct mode set - as if the motion sensing wasn't on ("+" button toggles that in the example). 

When you open a new issue, please:

- Describe which Wiimote you have (genuine Nintendo, some kind of clone)
- Describe your environment - which OS/version, how did  you connect the Wiimote to the PC, what kind of dongle (sometimes it matters). 
- Make sure you are running the latest Wiiuse code from here
- Compile Wiiuse in debug mode and post the output of the non-SDL example showing the problem.
